### PR TITLE
Update functionality to support pydantic 2.0+

### PR DESCRIPTION
**Pull request by HIL340**
**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] New Feature
- [x] Feature Improvement
- [ ] Refactoring
- [x] Documentation
- [ ] Other, please describe:

**Description:**

Since the breaking changes introduced upstream in Pydantic 2.0+, many of the features in this library have not been working correctly.

This PR updates the library and its showcase apps to support the latest Pydantic version (2.7).  

This should fix multiple reported issues with the showcase apps and any downstream apps that use anything but very basic functionality.

Fort reference this PR has been tested with: 
Pydantic: `2.7`
Python: `3.11`
Streamlit: `1.33.0`

Earlier versions of these *might* work but are untested.

**Change Summary**:
The majority of the changes are self explanatory.  Many pydantic functions and structures that this library relied on have changed or have been deprecated upstream. 

There are some more significant changes though that should be noted before merging:

1. The custom `FileContent` type has been removed in favour of the pydantics 2.0+ built in `Base64UrlBytes`.  The resulting empty `types.py` and its documentation have been removed (maybe this is bad idea). (see `examples/complex_showcase.py`)
2. The handling of `DataClasses` has changed significantly in pydantic 2.0+ and this required more rework on the lib side.  As a result though the return of `DataClass` instances from `sp.pydantic_form()` is now properly supported (see `examples/dataclass_form.py`)
3. `sp.pydantic_output()` has been improved slightly to support more complex pydantic models but could still use more work.
4. Pydantic 2.0+handling of `Fields` tagged as `Optional` is significantly different (as mentioned in #50) and currently not supported within the library. Examples have been updated to remove the `Optional` tag.

**Checklist:**

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by HIL340** [comment]
Closes #55, #56, #53, #38

**Comment by LukasMasuch** [comment]
@HIL340 thanks for the contribution! 👍 I will take  a closer look later this week

**Comment by 0xDeadcell** [comment]
Any updates?

**Comment by alex-mlabs** [comment]
Used this as a way to test using the branch specific implementation.

pip uninstall streamlit_pydantic pydantic-settings
poetry remove streamlit_pydantic

pip install git+https://github.com/HIL340/streamlit-pydantic.git@pydantic-2.7
poetry add streamlit-pydantic@git+https://github.com/HIL340/streamlit-pydantic.git#pydantic-2.7

**Comment by thinkORo** [comment]
Is there an update on this? @LukasMasuch, where can we support you?

**Comment by pablodz** [comment]
> Used this as a way to test using the branch specific implementation.
> 
> pip uninstall streamlit_pydantic pydantic-settings poetry remove streamlit_pydantic
> 
> pip install git+https://github.com/HIL340/streamlit-pydantic.git@pydantic-2.7 poetry add streamlit-pydantic@git+https://github.com/HIL340/streamlit-pydantic.git#pydantic-2.7

very useful, thanks

**Comment by gaby** [comment]
@HIL340 I think the github actions versions need to be updated too. The `action/checkout` current version is v4, not v2. 

https://github.com/actions/checkout/releases/tag/v4.1.7

**Comment by HIL340** [comment]
@gaby I updated the `action/checkout` to v4 but it did not resolve the build issue.

**Comment by gaby** [comment]
@pablodz Agree the whole ci has to be refactored

**Comment by HIL340** [comment]
This PR is arguably already a bit large and my experience with GitHub actions is fairly limited.

If the CI needs significant rework anyway and as long as this PR is not making the situation worse I'd suggest merging this one in and tackling the CI issues in a separate PR.

**Comment by MatanRubin** [comment]
@HIL340 , I agree. I also tested this change locally and can confirm it works. 
There are still a ton of issues we need to solve, but this is definitely a step forward.
@LukasMasuch , should I merge this? (and, as a general question, do you want me to freely make changes and merge PRs, or do you want to be the one to approve all PRs before they're merged?)

**Review by LukasMasuch — APPROVED** [review]

**Comment by LukasMasuch** [comment]
@MatanRubin 
> and, as a general question, do you want me to freely make changes and merge PRs, or do you want to be the one to approve all PRs before they're merged?

I configured it so that changes to `main` will require a PR that is approved by at least one other person (it does not have to be me). I'm happy also to add more maintainers if anyone is interested :)

**Pull request merged**
